"""FastAPI 对外输入输出模型。"""

from src.schemas.room import (
    AbilityIncreaseRequest,
    CharacterDraft,
    CharacterSummary,
    ClueView,
    CreateRoomRequest,
    DiceRollRequest,
    DiceRollResult,
    InteractionRollResponse,
    JoinRoomRequest,
    MemberView,
    PendingInteractionView,
    RoomActionRequest,
    RoomAuthResponse,
    RoomEvent,
    RoomLobbyView,
    RoomView,
    SceneView,
    SendMessageRequest,
    SessionView,
    StartRoomRequest,
    TimelineEntry,
)

__all__ = [
    "AbilityIncreaseRequest",
    "CharacterDraft",
    "CharacterSummary",
    "ClueView",
    "CreateRoomRequest",
    "DiceRollRequest",
    "DiceRollResult",
    "InteractionRollResponse",
    "JoinRoomRequest",
    "MemberView",
    "PendingInteractionView",
    "RoomActionRequest",
    "RoomAuthResponse",
    "RoomEvent",
    "RoomLobbyView",
    "RoomView",
    "SceneView",
    "SendMessageRequest",
    "SessionView",
    "StartRoomRequest",
    "TimelineEntry",
]
